TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files

DATA += devHFMAGPSU.proto

#=======================================
include $(TOP)/configure/RULES
